platform :ios, '8.0'

target ‘Podinns' do
pod 'AFNetworking', '~> 3.1.0'
pod 'MJExtension', '~> 3.0.13'
pod 'FMDB', '~> 2.6.2'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'Masonry', '~> 1.0.2'
pod 'ReactiveCocoa', '~> 2.5'
#调试App
pod 'FLEX', '~> 2.4.0'
end


